[2023-09-30T16:30:33.006+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.list_issues_task manual__2023-09-30T16:30:28.231216+00:00 [queued]>
[2023-09-30T16:30:33.019+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.list_issues_task manual__2023-09-30T16:30:28.231216+00:00 [queued]>
[2023-09-30T16:30:33.019+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-30T16:30:33.020+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-30T16:30:33.020+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-30T16:30:33.033+0000] {taskinstance.py:1300} INFO - Executing <Task(SimpleHttpOperator): list_issues_task> on 2023-09-30 16:30:28.231216+00:00
[2023-09-30T16:30:33.066+0000] {standard_task_runner.py:55} INFO - Started process 1011 to run task
[2023-09-30T16:30:33.077+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'list_issues_task', 'manual__2023-09-30T16:30:28.231216+00:00', '--job-id', '233', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpt2jcfmqc']
[2023-09-30T16:30:33.081+0000] {standard_task_runner.py:83} INFO - Job 233: Subtask list_issues_task
[2023-09-30T16:30:33.156+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.list_issues_task manual__2023-09-30T16:30:28.231216+00:00 [running]> on host 48572125e3d1
[2023-09-30T16:30:33.232+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=list_issues_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-30T16:30:28.231216+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-30T16:30:28.231216+00:00
[2023-09-30T16:30:33.233+0000] {http.py:123} INFO - Calling HTTP method
[2023-09-30T16:30:33.245+0000] {base.py:73} INFO - Using connection ID 'github_api_connection' for task execution.
[2023-09-30T16:30:33.726+0000] {http.py:163} ERROR - HTTP error: Not Found
[2023-09-30T16:30:33.727+0000] {http.py:164} ERROR - Not Found
[2023-09-30T16:30:33.743+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 161, in check_response
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/DRAJ6/Airflow-GitHub/repos/DRAJ6/Airflow-GitHub/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 125, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 151, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 204, in run_and_check
    self.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 165, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 404:Not Found
[2023-09-30T16:30:33.748+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=list_issues_task, execution_date=20230930T163028, start_date=20230930T163033, end_date=20230930T163033
[2023-09-30T16:30:33.762+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 233 for task list_issues_task (404:Not Found; 1011)
[2023-09-30T16:30:33.794+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-30T16:30:33.823+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
