[2023-09-19T01:57:53.928+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.build_save_model_task manual__2023-09-19T01:57:44.089073+00:00 [queued]>
[2023-09-19T01:57:53.936+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.build_save_model_task manual__2023-09-19T01:57:44.089073+00:00 [queued]>
[2023-09-19T01:57:53.937+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-19T01:57:53.937+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-19T01:57:53.937+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-19T01:57:53.949+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2023-09-19 01:57:44.089073+00:00
[2023-09-19T01:57:53.969+0000] {standard_task_runner.py:55} INFO - Started process 1812 to run task
[2023-09-19T01:57:53.975+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'build_save_model_task', 'manual__2023-09-19T01:57:44.089073+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpit9lvbvc']
[2023-09-19T01:57:53.983+0000] {standard_task_runner.py:83} INFO - Job 193: Subtask build_save_model_task
[2023-09-19T01:57:54.160+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.build_save_model_task manual__2023-09-19T01:57:44.089073+00:00 [running]> on host eef19852759c
[2023-09-19T01:57:54.424+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=build_save_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T01:57:44.089073+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-19T01:57:44.089073+00:00
[2023-09-19T01:59:18.405+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab2.py", line 65, in build_save_model
    val = (sse[i] - sse[i + 1]) / (sse[i - 1] - sse[i])
IndexError: list index out of range
[2023-09-19T01:59:18.469+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=build_save_model_task, execution_date=20230919T015744, start_date=20230919T015753, end_date=20230919T015918
[2023-09-19T01:59:18.507+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 193 for task build_save_model_task (list index out of range; 1812)
[2023-09-19T01:59:18.535+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-19T01:59:18.575+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
