[2023-09-17T19:34:58.704+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:34:52.792358+00:00 [queued]>
[2023-09-17T19:34:58.713+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:34:52.792358+00:00 [queued]>
[2023-09-17T19:34:58.714+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T19:34:58.714+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-17T19:34:58.714+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T19:34:58.726+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): data_preprocessing_task> on 2023-09-17 19:34:52.792358+00:00
[2023-09-17T19:34:58.739+0000] {standard_task_runner.py:55} INFO - Started process 4546 to run task
[2023-09-17T19:34:58.745+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'data_preprocessing_task', 'manual__2023-09-17T19:34:52.792358+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpr0784msr']
[2023-09-17T19:34:58.750+0000] {standard_task_runner.py:83} INFO - Job 55: Subtask data_preprocessing_task
[2023-09-17T19:34:58.851+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:34:52.792358+00:00 [running]> on host 80c059a34b8e
[2023-09-17T19:34:59.064+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=data_preprocessing_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-17T19:34:52.792358+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-17T19:34:52.792358+00:00
[2023-09-17T19:34:59.066+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab2.py", line 29, in data_preprocessing
    data = data.dropna()
AttributeError: 'str' object has no attribute 'dropna'
[2023-09-17T19:34:59.080+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=data_preprocessing_task, execution_date=20230917T193452, start_date=20230917T193458, end_date=20230917T193459
[2023-09-17T19:34:59.092+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 55 for task data_preprocessing_task ('str' object has no attribute 'dropna'; 4546)
[2023-09-17T19:34:59.117+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-17T19:34:59.153+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
