[2023-09-17T21:22:26.798+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.load_model_task manual__2023-09-17T21:22:24.641981+00:00 [queued]>
[2023-09-17T21:22:26.805+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.load_model_task manual__2023-09-17T21:22:24.641981+00:00 [queued]>
[2023-09-17T21:22:26.805+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T21:22:26.805+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-17T21:22:26.805+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T21:22:26.813+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_model_task> on 2023-09-17 21:22:24.641981+00:00
[2023-09-17T21:22:26.824+0000] {standard_task_runner.py:55} INFO - Started process 646 to run task
[2023-09-17T21:22:26.828+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'load_model_task', 'manual__2023-09-17T21:22:24.641981+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp7btnq_0c']
[2023-09-17T21:22:26.835+0000] {standard_task_runner.py:83} INFO - Job 115: Subtask load_model_task
[2023-09-17T21:22:26.905+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.load_model_task manual__2023-09-17T21:22:24.641981+00:00 [running]> on host b55550b47356
[2023-09-17T21:22:26.956+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=load_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-17T21:22:24.641981+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-17T21:22:24.641981+00:00
[2023-09-17T21:22:26.957+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab2.py", line 95, in load_model
    loaded_model = pickle.load(open(filename, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'model2.sav'
[2023-09-17T21:22:26.966+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=load_model_task, execution_date=20230917T212224, start_date=20230917T212226, end_date=20230917T212226
[2023-09-17T21:22:26.973+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 115 for task load_model_task ([Errno 2] No such file or directory: 'model2.sav'; 646)
[2023-09-17T21:22:27.001+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-17T21:22:27.026+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
