[2023-09-17T20:12:12.147+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.build_save_model_task manual__2023-09-17T20:12:06.757924+00:00 [queued]>
[2023-09-17T20:12:12.155+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.build_save_model_task manual__2023-09-17T20:12:06.757924+00:00 [queued]>
[2023-09-17T20:12:12.155+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T20:12:12.156+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-17T20:12:12.156+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T20:12:12.166+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2023-09-17 20:12:06.757924+00:00
[2023-09-17T20:12:12.174+0000] {standard_task_runner.py:55} INFO - Started process 6672 to run task
[2023-09-17T20:12:12.179+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'build_save_model_task', 'manual__2023-09-17T20:12:06.757924+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp2jy5j0li']
[2023-09-17T20:12:12.181+0000] {standard_task_runner.py:83} INFO - Job 90: Subtask build_save_model_task
[2023-09-17T20:12:12.275+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.build_save_model_task manual__2023-09-17T20:12:06.757924+00:00 [running]> on host 80c059a34b8e
[2023-09-17T20:12:12.393+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=build_save_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-17T20:12:06.757924+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-17T20:12:06.757924+00:00
[2023-09-17T20:12:12.395+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab2.py", line 51, in build_save_model
    kmeans.fit(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 1143, in fit
    accept_large_sparse=False,
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 746, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
ValueError: could not convert string to float: '          BALANCE  PURCHASES  CREDIT_LIMIT\n0       40.900749      95.40        1000.0\n1     3202.467416       0.00        7000.0\n2     2495.148862     773.17        7500.0\n4      817.714335      16.00        1200.0\n5     1809.828751    1333.28        1800.0\n...           ...        ...           ...\n8943     5.871712      20.90         500.0\n8945    28.493517     291.12        1000.0\n8947    23.398673     144.40        1000.0\n8948    13.457564       0.00         500.0\n8949   372.708075    1093.25        1200.0\n\n[8636 rows x 3 columns]'
[2023-09-17T20:12:12.409+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=build_save_model_task, execution_date=20230917T201206, start_date=20230917T201212, end_date=20230917T201212
[2023-09-17T20:12:12.419+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 90 for task build_save_model_task (could not convert string to float: '          BALANCE  PURCHASES  CREDIT_LIMIT\n0       40.900749      95.40        1000.0\n1     3202.467416       0.00        7000.0\n2     2495.148862     773.17        7500.0\n4      817.714335      16.00        1200.0\n5     1809.828751    1333.28        1800.0\n...           ...        ...           ...\n8943     5.871712      20.90         500.0\n8945    28.493517     291.12        1000.0\n8947    23.398673     144.40        1000.0\n8948    13.457564       0.00         500.0\n8949   372.708075    1093.25        1200.0\n\n[8636 rows x 3 columns]'; 6672)
[2023-09-17T20:12:12.432+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-17T20:12:12.461+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
