[2023-09-30T20:33:40.371+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-09-30T20:33:35.971356+00:00 [queued]>
[2023-09-30T20:33:40.376+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-09-30T20:33:35.971356+00:00 [queued]>
[2023-09-30T20:33:40.377+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-30T20:33:40.377+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-30T20:33:40.377+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-30T20:33:40.384+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2023-09-30 20:33:35.971356+00:00
[2023-09-30T20:33:40.389+0000] {standard_task_runner.py:55} INFO - Started process 1258 to run task
[2023-09-30T20:33:40.392+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow-GitHub', 'build_save_model_task', 'manual__2023-09-30T20:33:35.971356+00:00', '--job-id', '284', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmplz105ndq']
[2023-09-30T20:33:40.394+0000] {standard_task_runner.py:83} INFO - Job 284: Subtask build_save_model_task
[2023-09-30T20:33:40.438+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-09-30T20:33:35.971356+00:00 [running]> on host 4b91a1d2327d
[2023-09-30T20:33:40.464+0000] {abstractoperator.py:613} ERROR - Exception rendering Jinja template for task 'build_save_model_task', field 'op_args'. Template: [XComArg(<Task(PythonOperator): data_preprocessing_task>, 'X_train'), XComArg(<Task(PythonOperator): data_preprocessing_task>, 'X_test'), XComArg(<Task(PythonOperator): data_preprocessing_task>, 'y_train'), XComArg(<Task(PythonOperator): data_preprocessing_task>, 'y_test'), 'model2.sav']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 674, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 674, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 666, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 342, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from data_preprocessing_task at Airflow-GitHub with key="X_train" is not found!
[2023-09-30T20:33:40.474+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 674, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 674, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 666, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 342, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from data_preprocessing_task at Airflow-GitHub with key="X_train" is not found!
[2023-09-30T20:33:40.478+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Airflow-GitHub, task_id=build_save_model_task, execution_date=20230930T203335, start_date=20230930T203340, end_date=20230930T203340
[2023-09-30T20:33:40.484+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 284 for task build_save_model_task (XComArg result from data_preprocessing_task at Airflow-GitHub with key="X_train" is not found!; 1258)
[2023-09-30T20:33:40.524+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-30T20:33:40.545+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
