[2023-09-17T19:40:17.561+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:40:09.253428+00:00 [queued]>
[2023-09-17T19:40:17.570+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:40:09.253428+00:00 [queued]>
[2023-09-17T19:40:17.571+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T19:40:17.571+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-17T19:40:17.571+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T19:40:17.584+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): data_preprocessing_task> on 2023-09-17 19:40:09.253428+00:00
[2023-09-17T19:40:17.599+0000] {standard_task_runner.py:55} INFO - Started process 4850 to run task
[2023-09-17T19:40:17.605+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'data_preprocessing_task', 'manual__2023-09-17T19:40:09.253428+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpovvk4vv9']
[2023-09-17T19:40:17.612+0000] {standard_task_runner.py:83} INFO - Job 59: Subtask data_preprocessing_task
[2023-09-17T19:40:17.769+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:40:09.253428+00:00 [running]> on host 80c059a34b8e
[2023-09-17T19:40:17.975+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=data_preprocessing_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-17T19:40:09.253428+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-17T19:40:09.253428+00:00
[2023-09-17T19:40:17.977+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab2.py", line 30, in data_preprocessing
    clustering_data = data["BALANCE", "PURCHASES", "CREDIT_LIMIT"]
TypeError: string indices must be integers
[2023-09-17T19:40:17.990+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=data_preprocessing_task, execution_date=20230917T194009, start_date=20230917T194017, end_date=20230917T194017
[2023-09-17T19:40:18.000+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 59 for task data_preprocessing_task (string indices must be integers; 4850)
[2023-09-17T19:40:18.028+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-17T19:40:18.092+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
