[2023-09-30T17:30:17.638+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.load_model_task manual__2023-09-30T17:30:02.466080+00:00 [queued]>
[2023-09-30T17:30:17.646+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.load_model_task manual__2023-09-30T17:30:02.466080+00:00 [queued]>
[2023-09-30T17:30:17.646+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-30T17:30:17.646+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-30T17:30:17.646+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-30T17:30:17.658+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_model_task> on 2023-09-30 17:30:02.466080+00:00
[2023-09-30T17:30:17.666+0000] {standard_task_runner.py:55} INFO - Started process 4172 to run task
[2023-09-30T17:30:17.670+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'load_model_task', 'manual__2023-09-30T17:30:02.466080+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpk5e825tg']
[2023-09-30T17:30:17.673+0000] {standard_task_runner.py:83} INFO - Job 254: Subtask load_model_task
[2023-09-30T17:30:17.746+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.load_model_task manual__2023-09-30T17:30:02.466080+00:00 [running]> on host 48572125e3d1
[2023-09-30T17:30:17.850+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=load_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-30T17:30:02.466080+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-30T17:30:02.466080+00:00
[2023-09-30T17:30:17.866+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but KMeans was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

[2023-09-30T17:30:17.947+0000] {python.py:177} INFO - Done. Returned value was: Cluster 14
[2023-09-30T17:30:17.987+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=your_python_dag, task_id=load_model_task, execution_date=20230930T173002, start_date=20230930T173017, end_date=20230930T173017
[2023-09-30T17:30:18.045+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-09-30T17:30:18.085+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
