[2023-09-19T01:54:58.976+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.build_save_model_task manual__2023-09-19T01:54:50.209389+00:00 [queued]>
[2023-09-19T01:54:58.989+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.build_save_model_task manual__2023-09-19T01:54:50.209389+00:00 [queued]>
[2023-09-19T01:54:58.989+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-19T01:54:58.989+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-19T01:54:58.990+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-19T01:54:59.002+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2023-09-19 01:54:50.209389+00:00
[2023-09-19T01:54:59.025+0000] {standard_task_runner.py:55} INFO - Started process 1630 to run task
[2023-09-19T01:54:59.031+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'build_save_model_task', 'manual__2023-09-19T01:54:50.209389+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpuf5197e_']
[2023-09-19T01:54:59.034+0000] {standard_task_runner.py:83} INFO - Job 190: Subtask build_save_model_task
[2023-09-19T01:54:59.112+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.build_save_model_task manual__2023-09-19T01:54:50.209389+00:00 [running]> on host eef19852759c
[2023-09-19T01:54:59.250+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=build_save_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T01:54:50.209389+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-19T01:54:50.209389+00:00
[2023-09-19T01:56:10.899+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab2.py", line 65, in build_save_model
    val = (dist[i] - dist[i + 1]) / (dist[i - 1] - dist[i])
NameError: name 'dist' is not defined
[2023-09-19T01:56:11.004+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=build_save_model_task, execution_date=20230919T015450, start_date=20230919T015458, end_date=20230919T015610
[2023-09-19T01:56:11.071+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 190 for task build_save_model_task (name 'dist' is not defined; 1630)
[2023-09-19T01:56:11.150+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-19T01:56:11.237+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
