[2023-10-05T17:06:01.353+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-05T17:05:47.874555+00:00 [queued]>
[2023-10-05T17:06:01.361+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-05T17:05:47.874555+00:00 [queued]>
[2023-10-05T17:06:01.361+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T17:06:01.361+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-10-05T17:06:01.361+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T17:06:01.373+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2023-10-05 17:05:47.874555+00:00
[2023-10-05T17:06:01.396+0000] {standard_task_runner.py:55} INFO - Started process 314 to run task
[2023-10-05T17:06:01.400+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow-GitHub', 'build_save_model_task', 'manual__2023-10-05T17:05:47.874555+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmppx2af2wn']
[2023-10-05T17:06:01.403+0000] {standard_task_runner.py:83} INFO - Job 356: Subtask build_save_model_task
[2023-10-05T17:06:01.471+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-05T17:05:47.874555+00:00 [running]> on host 38f4e1e9bdb5
[2023-10-05T17:06:01.563+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dheeraj
AIRFLOW_CTX_DAG_ID=Airflow-GitHub
AIRFLOW_CTX_TASK_ID=build_save_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-05T17:05:47.874555+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-05T17:05:47.874555+00:00
[2023-10-05T17:06:01.703+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:1333: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-10-05T17:06:01.703+0000] {logging_mixin.py:137} INFO - Fitting 10 folds for each of 64 candidates, totalling 640 fits
[2023-10-05T17:06:03.572+0000] {logging_mixin.py:137} INFO - Best parameters: {'C': 0.6, 'class_weight': {1: 0.5, 0: 0.5}, 'penalty': 'l2', 'solver': 'saga'}
[2023-10-05T17:06:03.588+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-10-05T17:06:03.643+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=Airflow-GitHub, task_id=build_save_model_task, execution_date=20231005T170547, start_date=20231005T170601, end_date=20231005T170603
[2023-10-05T17:06:03.783+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-10-05T17:06:03.879+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
