[2023-09-17T19:32:52.101+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:32:46.364021+00:00 [queued]>
[2023-09-17T19:32:52.109+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:32:46.364021+00:00 [queued]>
[2023-09-17T19:32:52.109+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T19:32:52.110+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-17T19:32:52.110+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T19:32:52.120+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): data_preprocessing_task> on 2023-09-17 19:32:46.364021+00:00
[2023-09-17T19:32:52.134+0000] {standard_task_runner.py:55} INFO - Started process 4411 to run task
[2023-09-17T19:32:52.139+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'data_preprocessing_task', 'manual__2023-09-17T19:32:46.364021+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp9ilcnr3z']
[2023-09-17T19:32:52.142+0000] {standard_task_runner.py:83} INFO - Job 53: Subtask data_preprocessing_task
[2023-09-17T19:32:52.227+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T19:32:46.364021+00:00 [running]> on host 80c059a34b8e
[2023-09-17T19:32:52.358+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=data_preprocessing_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-17T19:32:46.364021+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-17T19:32:46.364021+00:00
[2023-09-17T19:32:52.360+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab2.py", line 28, in data_preprocessing
    data.isnull().sum()
AttributeError: 'str' object has no attribute 'isnull'
[2023-09-17T19:32:52.377+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=data_preprocessing_task, execution_date=20230917T193246, start_date=20230917T193252, end_date=20230917T193252
[2023-09-17T19:32:52.388+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 53 for task data_preprocessing_task ('str' object has no attribute 'isnull'; 4411)
[2023-09-17T19:32:52.431+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-17T19:32:52.469+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
