[2023-10-05T17:10:02.573+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-05T17:09:54.067802+00:00 [queued]>
[2023-10-05T17:10:02.602+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-05T17:09:54.067802+00:00 [queued]>
[2023-10-05T17:10:02.603+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T17:10:02.603+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-10-05T17:10:02.603+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T17:10:02.619+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2023-10-05 17:09:54.067802+00:00
[2023-10-05T17:10:02.702+0000] {standard_task_runner.py:55} INFO - Started process 595 to run task
[2023-10-05T17:10:02.707+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow-GitHub', 'build_save_model_task', 'manual__2023-10-05T17:09:54.067802+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp16bbmwk7']
[2023-10-05T17:10:02.710+0000] {standard_task_runner.py:83} INFO - Job 365: Subtask build_save_model_task
[2023-10-05T17:10:02.786+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-05T17:09:54.067802+00:00 [running]> on host 38f4e1e9bdb5
[2023-10-05T17:10:02.867+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dheeraj
AIRFLOW_CTX_DAG_ID=Airflow-GitHub
AIRFLOW_CTX_TASK_ID=build_save_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-05T17:09:54.067802+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-05T17:09:54.067802+00:00
[2023-10-05T17:10:02.972+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:1333: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-10-05T17:10:02.972+0000] {logging_mixin.py:137} INFO - Fitting 10 folds for each of 64 candidates, totalling 640 fits
[2023-10-05T17:10:04.376+0000] {logging_mixin.py:137} INFO - Best parameters: {'C': 0.6, 'class_weight': {1: 0.5, 0: 0.5}, 'penalty': 'l2', 'solver': 'saga'}
[2023-10-05T17:10:04.382+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-10-05T17:10:04.399+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=Airflow-GitHub, task_id=build_save_model_task, execution_date=20231005T170954, start_date=20231005T171002, end_date=20231005T171004
[2023-10-05T17:10:04.431+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-10-05T17:10:04.473+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
