[2023-09-30T20:36:01.007+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-09-30T20:35:53.976765+00:00 [queued]>
[2023-09-30T20:36:01.013+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-09-30T20:35:53.976765+00:00 [queued]>
[2023-09-30T20:36:01.013+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-30T20:36:01.013+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-30T20:36:01.013+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-30T20:36:01.021+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2023-09-30 20:35:53.976765+00:00
[2023-09-30T20:36:01.045+0000] {standard_task_runner.py:55} INFO - Started process 1413 to run task
[2023-09-30T20:36:01.057+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow-GitHub', 'build_save_model_task', 'manual__2023-09-30T20:35:53.976765+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp_9j6jc_8']
[2023-09-30T20:36:01.061+0000] {standard_task_runner.py:83} INFO - Job 287: Subtask build_save_model_task
[2023-09-30T20:36:01.135+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-09-30T20:35:53.976765+00:00 [running]> on host 4b91a1d2327d
[2023-09-30T20:36:01.217+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dheeraj
AIRFLOW_CTX_DAG_ID=Airflow-GitHub
AIRFLOW_CTX_TASK_ID=build_save_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-30T20:35:53.976765+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-30T20:35:53.976765+00:00
[2023-09-30T20:36:01.219+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/airflow_github.py", line 69, in build_model
    lr_cv.fit(X_train, y_train)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 802, in fit
    cv_orig = check_cv(self.cv, y, classifier=is_classifier(estimator))
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 2303, in check_cv
    and (type_of_target(y) in ("binary", "multiclass"))
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 271, in type_of_target
    "Expected array-like (array or non-string sequence), got %r" % y
ValueError: Expected array-like (array or non-string sequence), got 'None'
[2023-09-30T20:36:01.229+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Airflow-GitHub, task_id=build_save_model_task, execution_date=20230930T203553, start_date=20230930T203601, end_date=20230930T203601
[2023-09-30T20:36:01.235+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 287 for task build_save_model_task (Expected array-like (array or non-string sequence), got 'None'; 1413)
[2023-09-30T20:36:01.267+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-30T20:36:01.289+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
