[2023-09-17T21:35:47.183+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.elbow_task manual__2023-09-17T21:35:00.442896+00:00 [queued]>
[2023-09-17T21:35:47.193+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.elbow_task manual__2023-09-17T21:35:00.442896+00:00 [queued]>
[2023-09-17T21:35:47.193+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T21:35:47.193+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-17T21:35:47.194+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T21:35:47.203+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): elbow_task> on 2023-09-17 21:35:00.442896+00:00
[2023-09-17T21:35:47.212+0000] {standard_task_runner.py:55} INFO - Started process 1551 to run task
[2023-09-17T21:35:47.217+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'elbow_task', 'manual__2023-09-17T21:35:00.442896+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpcph87fam']
[2023-09-17T21:35:47.222+0000] {standard_task_runner.py:83} INFO - Job 134: Subtask elbow_task
[2023-09-17T21:35:47.317+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.elbow_task manual__2023-09-17T21:35:00.442896+00:00 [running]> on host b55550b47356
[2023-09-17T21:35:47.407+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=elbow_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-17T21:35:00.442896+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-17T21:35:00.442896+00:00
[2023-09-17T21:35:47.409+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab2.py", line 82, in elbow
    range(1, 50), sse, curve="convex", direction="decreasing"
  File "/home/airflow/.local/lib/python3.7/site-packages/kneed/knee_locator.py", line 171, in __init__
    uspline = interpolate.interp1d(self.x, self.y)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 436, in __init__
    _Interpolator1D.__init__(self, x, y, axis=axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/interpolate/polyint.py", line 54, in __init__
    self._set_yi(yi, xi=xi, axis=axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/interpolate/polyint.py", line 124, in _set_yi
    raise ValueError("x and y arrays must be equal in length along "
ValueError: x and y arrays must be equal in length along interpolation axis.
[2023-09-17T21:35:47.423+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=elbow_task, execution_date=20230917T213500, start_date=20230917T213547, end_date=20230917T213547
[2023-09-17T21:35:47.432+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 134 for task elbow_task (x and y arrays must be equal in length along interpolation axis.; 1551)
[2023-09-17T21:35:47.473+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-17T21:35:47.488+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
