[2023-09-17T20:06:25.438+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T20:06:20.224727+00:00 [queued]>
[2023-09-17T20:06:25.451+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T20:06:20.224727+00:00 [queued]>
[2023-09-17T20:06:25.452+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T20:06:25.452+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-17T20:06:25.453+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T20:06:25.466+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): data_preprocessing_task> on 2023-09-17 20:06:20.224727+00:00
[2023-09-17T20:06:25.479+0000] {standard_task_runner.py:55} INFO - Started process 6327 to run task
[2023-09-17T20:06:25.485+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'data_preprocessing_task', 'manual__2023-09-17T20:06:20.224727+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpxzd8pzkr']
[2023-09-17T20:06:25.491+0000] {standard_task_runner.py:83} INFO - Job 87: Subtask data_preprocessing_task
[2023-09-17T20:06:25.562+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.data_preprocessing_task manual__2023-09-17T20:06:20.224727+00:00 [running]> on host 80c059a34b8e
[2023-09-17T20:06:25.705+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=data_preprocessing_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-17T20:06:20.224727+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-17T20:06:20.224727+00:00
[2023-09-17T20:06:25.707+0000] {logging_mixin.py:137} INFO - <class 'str'>
[2023-09-17T20:06:25.707+0000] {logging_mixin.py:137} INFO - ahbd
[2023-09-17T20:06:25.707+0000] {logging_mixin.py:137} INFO -      CUST_ID      BALANCE  ...  PRC_FULL_PAYMENT  TENURE
0     C10001    40.900749  ...          0.000000      12
1     C10002  3202.467416  ...          0.222222      12
2     C10003  2495.148862  ...          0.000000      12
4     C10005   817.714335  ...          0.000000      12
5     C10006  1809.828751  ...          0.000000      12
...      ...          ...  ...               ...     ...
8943  C19184     5.871712  ...          0.000000       6
8945  C19186    28.493517  ...          0.500000       6
8947  C19188    23.398673  ...          0.250000       6
8948  C19189    13.457564  ...          0.250000       6
8949  C19190   372.708075  ...          0.000000       6

[8636 rows x 18 columns]
[2023-09-17T20:06:25.709+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab2.py", line 35, in data_preprocessing
    data_df = pd.read_csv(io.StringIO(data), sep=' ')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 28 fields in line 7, saw 39

[2023-09-17T20:06:25.723+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=data_preprocessing_task, execution_date=20230917T200620, start_date=20230917T200625, end_date=20230917T200625
[2023-09-17T20:06:25.733+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 87 for task data_preprocessing_task (Error tokenizing data. C error: Expected 28 fields in line 7, saw 39
; 6327)
[2023-09-17T20:06:25.778+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-17T20:06:25.805+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
