[2023-10-05T17:06:32.799+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-05T17:06:24.159082+00:00 [queued]>
[2023-10-05T17:06:32.805+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-05T17:06:24.159082+00:00 [queued]>
[2023-10-05T17:06:32.806+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T17:06:32.806+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-10-05T17:06:32.806+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T17:06:32.815+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2023-10-05 17:06:24.159082+00:00
[2023-10-05T17:06:32.824+0000] {standard_task_runner.py:55} INFO - Started process 366 to run task
[2023-10-05T17:06:32.828+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow-GitHub', 'build_save_model_task', 'manual__2023-10-05T17:06:24.159082+00:00', '--job-id', '361', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmph1pse4go']
[2023-10-05T17:06:32.831+0000] {standard_task_runner.py:83} INFO - Job 361: Subtask build_save_model_task
[2023-10-05T17:06:32.895+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-05T17:06:24.159082+00:00 [running]> on host 38f4e1e9bdb5
[2023-10-05T17:06:32.993+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dheeraj
AIRFLOW_CTX_DAG_ID=Airflow-GitHub
AIRFLOW_CTX_TASK_ID=build_save_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-05T17:06:24.159082+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-05T17:06:24.159082+00:00
[2023-10-05T17:06:33.071+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:1333: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-10-05T17:06:33.071+0000] {logging_mixin.py:137} INFO - Fitting 10 folds for each of 64 candidates, totalling 640 fits
[2023-10-05T17:06:34.464+0000] {logging_mixin.py:137} INFO - Best parameters: {'C': 0.6, 'class_weight': {1: 0.5, 0: 0.5}, 'penalty': 'l2', 'solver': 'saga'}
[2023-10-05T17:06:34.469+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/airflow_github.py", line 81, in build_model
    pickle.dump(lr_clf, open(os.path.join(os.path.dirname(__file__), "../model/test"), 'wb'))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/src/../model/test'
[2023-10-05T17:06:34.479+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Airflow-GitHub, task_id=build_save_model_task, execution_date=20231005T170624, start_date=20231005T170632, end_date=20231005T170634
[2023-10-05T17:06:34.490+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 361 for task build_save_model_task ([Errno 2] No such file or directory: '/opt/airflow/dags/src/../model/test'; 366)
[2023-10-05T17:06:34.518+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-10-05T17:06:34.539+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
