[2023-09-17T21:41:17.322+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.elbow_task manual__2023-09-17T21:40:30.055615+00:00 [queued]>
[2023-09-17T21:41:17.328+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: your_python_dag.elbow_task manual__2023-09-17T21:40:30.055615+00:00 [queued]>
[2023-09-17T21:41:17.328+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T21:41:17.328+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-17T21:41:17.329+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-17T21:41:17.336+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): elbow_task> on 2023-09-17 21:40:30.055615+00:00
[2023-09-17T21:41:17.341+0000] {standard_task_runner.py:55} INFO - Started process 1918 to run task
[2023-09-17T21:41:17.344+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'your_python_dag', 'elbow_task', 'manual__2023-09-17T21:40:30.055615+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpq2fak_c4']
[2023-09-17T21:41:17.346+0000] {standard_task_runner.py:83} INFO - Job 139: Subtask elbow_task
[2023-09-17T21:41:17.408+0000] {task_command.py:388} INFO - Running <TaskInstance: your_python_dag.elbow_task manual__2023-09-17T21:40:30.055615+00:00 [running]> on host b55550b47356
[2023-09-17T21:41:17.471+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=your_python_dag
AIRFLOW_CTX_TASK_ID=elbow_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-17T21:40:30.055615+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-17T21:40:30.055615+00:00
[2023-09-17T21:41:17.472+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab2.py", line 82, in elbow
    range(1, 50), sse, curve="convex", direction="decreasing"
  File "/home/airflow/.local/lib/python3.7/site-packages/kneed/knee_locator.py", line 171, in __init__
    uspline = interpolate.interp1d(self.x, self.y)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 436, in __init__
    _Interpolator1D.__init__(self, x, y, axis=axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/interpolate/polyint.py", line 54, in __init__
    self._set_yi(yi, xi=xi, axis=axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/interpolate/polyint.py", line 124, in _set_yi
    raise ValueError("x and y arrays must be equal in length along "
ValueError: x and y arrays must be equal in length along interpolation axis.
[2023-09-17T21:41:17.483+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=your_python_dag, task_id=elbow_task, execution_date=20230917T214030, start_date=20230917T214117, end_date=20230917T214117
[2023-09-17T21:41:17.491+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 139 for task elbow_task (x and y arrays must be equal in length along interpolation axis.; 1918)
[2023-09-17T21:41:17.517+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-17T21:41:17.534+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
